### ISSUE TITLE
Bug with comment lines in ruby files

### ISSUE THREAD

**Issue by Chris24680** [ericadamski/atom-carbon-now-sh#2]
If you highlight a piece of ruby code with a comment in it. When carbon opens, only the code before that comment will be copied.

**Comment by ericadamski** [comment]
@Chris24680 thank you for taking the time to submit an issue. ❤️ Can you send me a line of code for which that happens, I can definitely fix that for you!

**Comment by Chris24680** [comment]
```
  def hello
    #this is my code
    1+1
  end
```

Highlighting this and calling carbon results in this image:

![carbon](https://user-images.githubusercontent.com/9864806/36318667-6fcdb122-1338-11e8-934a-7ca04e438444.png)

**Comment by ericadamski** [comment]
# Solution
We need to replace the literal `#` character with `%23` before we send it though the url since `window.encodeURI` doesn't do it automatically.
